import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Canvas from '../components/Canvas';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Paint app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-700 text-white'>
        <h1>Hello Canvas</h1>
        <Canvas />
      </main>
    </>
  );
};

export default Home;
