import type { NextPage } from 'next';
import Head from 'next/head';
import { useRef, useState } from 'react';
import Canvas from '../components/Canvas';
import ColorPicker from '../components/ColorPicker';
import Eraser from '../components/Eraser';
import StrokeWidthPicker from '../components/StrokeWidthPicker';
import Toolbar from '../components/Toolbar';

const Home: NextPage = () => {
  const [color, setColor] = useState('#000000');
  const [strokeWidth, setStrokeWidth] = useState(12);
  const [lineCap, setLineCap] = useState<CanvasLineCap>('round');

  return (
    <>
      <Head>
        <title>Paint app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-700 text-white min-h-screen flex justify-center items-center'>
        <Toolbar
          color={color}
          setColor={setColor}
          strokeWidth={strokeWidth}
          setStrokeWidth={setStrokeWidth}
          lineCap={lineCap}
          setLineCap={setLineCap}
        />
        <Canvas color={color} strokeWidth={strokeWidth} lineCap={lineCap} />
      </main>
    </>
  );
};

export default Home;
